[task]
deterministic = true

[requirements]
packages = []  

[inputs]
type = "range_continuous"

[inputs.range_continuous]
start = 1
end   = 2000000000
step  = 1

[outputs]
dir              = "outputs"
filename_pattern = "results_{start}_{end}.json"
